// GET USER
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLE = "GET_ARTICLE";
export const POST_ARTICLE = "POST_ARTICLE";
export const GET_USER = "GET_USER";

//CONSULTATION
export const POST_CONSULTATION = "POST_CONSULTATION";
export const GET_CONSULTATION = "GET_CONSULTATION";
export const GET_CONSULTATION_ID = "GET_CONSULTATION_ID";